### ISSUE TITLE
Remove `use_` from exported functions

### ISSUE THREAD

**Issue by llrs** [lcolladotor/biocthis#1]
Many thanks for developing this package! I've been looking for a while for a Bioconductor styler formatter. 

I think it would be easier to use if instead of `use_bioc_support()` would be only `bioc_support()` and alike. It won't conflict with `usethis` and will be shorter to read/understand. Alternatively it could use `add_`, `add_bioc_support, `add_issue_template`...

Also if you could explain better the differences between the `usethis` templates and this templates would be easier to adopt it (although having it recommended on the r-lib/actions will surely help).

**Comment by lcolladotor** [comment]
Hi Lluís,

The names of the functions do not conflict with `usethis` and I like the idea of having a verb in the function name. `usethis` already has functions with the prefix `use_tidy_*` so that's where `use_bioc_*` came to to be, plus it pays homage to where the functions are based from.

As for `r-lib/actions`, this PR https://github.com/r-lib/actions/pull/101 was just approved today.

Regarding explaining the differences, are you talking about adding more details to https://lcolladotor.github.io/biocthis/articles/biocthis.html#biocthis-functions-overview-1? Or the help pages for each function?

Best,
Leo

**Comment by llrs** [comment]
I mean adding more details on the help pages of each function. I mean if I go to the help page of `use_bioc_news_md` I can read "This function is very similar to usethis::use_news_md() except that it uses a template from biocthis." but that doesn't tell me what is different from the usethis template or how it is more appropiate for Bioconductor.  

I don't know the advantage of using `use_bioc_news_md` instead of `use_news_md`. I would like to know more about the templates before deciding applying them to the packages and I cannot do it just looking to the help pages. Just my 2 cents. 

Hope you are well on these days,

Lluís
