### ISSUE TITLE
Advice for Mac OS & Bioc devel `there is no package called ‘RSQLite`

### ISSUE THREAD

**Issue by mblue9** [lcolladotor/biocthis#15]
Hello,

Thanks for your GitHub actions workflow, it's been very useful, we've been using it successfully for the last few months.

We've now updated to using the current biocthis action version with Bioc devel and have an issue. Was wondering if you might have any advice? 

For Mac OSX we're getting a lot of packages (AnnotationDbi, GO.db, org.Hs.eg.db, genefilter) not installing due to `there is no package called ‘RSQLite` [here](https://github.com/stemangiola/tidybulk/runs/1383777402?check_suite_focus=true).

I haven't worked with R devel before so not sure, but is it because there's no RSQlite r-devel for Mac here https://cran.rstudio.com/web/packages/RSQLite/index.html

If so is there any recommended way to handle that in the action?

**Comment by lcolladotor** [comment]
Hi @mblue9,

From looking at the full logs, it looks like `RSQlite` does get installed properly on macOS but **after** other packages needed it. This can be a bit of a dependency installation issue, which is why I have the 2 lines for installing dependencies (https://github.com/stemangiola/tidybulk/blob/master/.github/workflows/check-bioc.yml#L195-L204 on your version, https://github.com/lcolladotor/biocthis/blob/master/.github/workflows/check-bioc.yml#L170-L176 on the latest version). You could try manually installing `RSQlite` prior to those attempts though and seeing if that fixes things. 

Note that you are using an older version of the GHA workflow. Check https://lcolladotor.github.io/biocthis/reference/use_bioc_github_action.html since the R function has a few new options.

Ultimately, right now the issue is that Bioc-devel (3.13) runs on R-devel (what will become R 4.1) and CRAN does not provide binaries for packages on R-devel meaning that everything has to be compiled on macOS and Windows, which can be a bit painful. If what you are testing is not really that dependent on BioC 3.13 or R-devel, you could instead test using BioC 3.12 (bioc-release, R 4.0 which CRAN has binaries for the packages) for quick tests while Bioconductor will run the tests on Bioc 3.13 and figure out the compilation issues. Having said that, it can be a learning experience to figure out the compilation issues yourself.

Best,
Leo

**Comment by mblue9** [comment]
Hi Leo,

Thanks for that info, it's very helpful!

Maria

**Comment by lcolladotor** [comment]
No problem =) Thanks for using `biocthis` ^^
