### ISSUE TITLE
[BUG] pkgdown site build fails within Docker containers

### ISSUE THREAD

**Issue by bschilder** [lcolladotor/biocthis#29]
[pkgdown site step](https://github.com/lcolladotor/biocthis/blob/341ae80706ecc2950e0a50bc36dc7416f2a5d173/.github/workflows/check-bioc.yml#L279) runs into error when using a Docker container. 

## Issue

This happens because of the [recent changes to git](https://github.com/actions/checkout/issues/760) regarding security.

Supposedly this has been fixed in regards to some GH actions, but apparently not all.  The suggested workaround doesn't work as-is and needs some adjusting:

<img width="936" alt="Screenshot 2022-04-26 at 11 42 50" src="https://user-images.githubusercontent.com/34280215/165282976-d5d350fb-1e1d-48c8-bae4-7e698d88b9e5.png">

## Solution

I've implement this in my adapted version of Biocthis's GHA workflow, seen [here](https://github.com/RajLabMSSM/echodata/blob/3d4544341de35f9a43fec661671d87515cb7be42/.github/workflows/check-bioc-docker.yml#L350). In the case of my [echodata](https://github.com/RajLabMSSM/echodata) R package, this solution seems to work well.

This involves an extra GHA step beforehand that extracts the R package name from the DESCRIPTION file. This is more robust than assuming that the repository has an identical name as the package itself, which is sometimes not the case due to differences in capitalization or use of "." vs "_".  You can see this step here:
https://github.com/RajLabMSSM/echodata/blob/3d4544341de35f9a43fec661671d87515cb7be42/.github/workflows/check-bioc-docker.yml#L325

## Other notes

Doesn't seem like Biocthis's GHA checks for itself are catching this error; do you run any GHA within a Docker container? If not, this would be quite helpful to have as it would ensure your workflow templates are running as expected both within and outside of containers.

Best, 
Brian

**Comment by lcolladotor** [comment]
Thanks for the report Brian! I'll look into it later this week. I'm a bit out of the loop on the Git security changes, so thanks for the link to https://github.com/actions/checkout/issues/760. 

I've encountered some git issues like at https://github.com/lcolladotor/team_surveys/commit/5fe88a94f9087659b1a12ada93b5bf9e98526c70 or the one you described (at https://github.com/LieberInstitute/spatialLIBD/runs/6114315548?check_suite_focus=true#step:28:27 in my case), which I simply dodged by disabling `pkgdown` since I didn't have time to deal with it then.

**Comment by bschilder** [comment]
Sounds good, let me know if you have any questions then.

**Comment by kevinrue** [comment]
I've just noted something more that is visible in the screenshot at the top of this thread:
The two `git config` commands:
```
  git config --local user.name "$GITHUB_ACTOR"
  git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
```
fail because they're run from the home directory (one level up from the git repo.

The errors (visible in the screenshot too) are

```
fatal: --local can only be used inside a git repository
fatal: --local can only be used inside a git repository
```

I'm not sure why those lines were not an issue before, but it sounds like the fix is either to `cd` into the subdirectory of the repo, or use `--global` instead

**Comment by lcolladotor** [comment]
FYI I've been away most of June as my father had an important surgery. I'll be back in the office on July 5th.

**Comment by lcolladotor** [comment]
Thanks everyone for this thread! This works again as you can see at https://github.com/lcolladotor/biocthis/actions/runs/3364123000/jobs/5578109324#step:30:90 ^^

I tried adapting some of https://github.com/r-lib/actions/blob/465e3c76cf4d432b547a0a411972939899c87857/examples/pkgdown.yaml#L40-L46 as suggested by you earlier, but also using `JamesIves/github-pages-deploy-action@releases/v4` (see #31 by @lmweber) instead of the specific version 4.4.1 at https://github.com/r-lib/actions/blob/465e3c76cf4d432b547a0a411972939899c87857/examples/pkgdown.yaml#L42. I had to add the installation of `rsync` as a system dependency to make this work.

It thus comes down to https://github.com/lcolladotor/biocthis/blob/5c38754d8bd2e44fe9c5486a665ac4429ef6f1b6/inst/templates/check-bioc.yml#L274-L298 in addition to using `checkout@v3`.

I saw that @kevinrue and @dzhang32 have a solution without using `pkgdown::build_site_github_pages()` (aka, still using `pkgdown::deploy_to_branch(new_process = FALSE)`). @kevinrue has it hardcoded while @dzhang32 adapted a solution by @RajLabMSSM that creates an environmental variable to determine the package name. This could have been done with the template utilities. But well, I thought it would be best to stay as close as possible to `r-lib/actionsexamples/pkgdown`. 

I did note the use of https://github.com/r-lib/actions/blob/465e3c76cf4d432b547a0a411972939899c87857/examples/pkgdown.yaml#L31-L34 which is documented at https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies, however, I thought it was simpler to only install `rsync`, given that we are building on top of the Bioconductor docker image and already have lots installed.

Best,
Leo
